# Generated by Django 3.1.1 on 2021-06-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='date',
        ),
    ]
