# Generated by Django 3.1.1 on 2021-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_remove_userentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='dose_type',
            field=models.IntegerField(default=1),
        ),
    ]
